version: '3.4'
networks:
  my-network:
    driver: bridge
services:
  super-app-db:
    container_name: super-app-db
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: bakkt-demo-db
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      #MYSQL_ROOT_PASSWORD: example
      #MYSQL_USER: myuser
      #MYSQL_PASSWORD: testpass
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - my-network

  springboot-restful-webservices:
      container_name: springboot-restful-webservices
      build:
         context: ./
         dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - super-app-db
      networks:
        - my-network
      restart: on-failure